default_platform(:ios)

platform :ios do
  desc "Build and Upload to App Store Connect"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_PRIVATE_KEY"],
      is_key_content_base64: false
    )

    setup_ci

    # 1. Update project team directly in the xcodeproj file
    update_project_team(
      path: "./ApnaConnect.xcodeproj",
      teamid: "5L2WJF5LMT" # Replace with your client's Team ID
    )

    # 2. Build app with -allowProvisioningUpdates flag
    build_app(
      scheme: "ApnaConnect",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates"
    )

    # 3. Upload to TestFlight
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end