default_platform(:ios)

platform :ios do

  lane :release do

    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_PRIVATE_KEY"],
      is_key_content_base64: false
    )

    update_code_signing_settings(
      path: "./ApnaConnect.xcodeproj",
      use_automatic_signing: false,
      team_id: ENV["TEAM_ID"],
      code_sign_identity: "Apple Distribution",
      profile_name: ENV["PROVISIONING_PROFILE_NAME"]
    )

    build_app(
      scheme: "ApnaConnect",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          "com.apnaconnect.ApnaConnect" => ENV["PROVISIONING_PROFILE_NAME"]
        }
      },
      xcargs: "DEVELOPMENT_TEAM=#{ENV['TEAM_ID']}"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )

  end

end